# Generated by Django 3.2.4 on 2021-06-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
