# Generated by Django 3.2.4 on 2021-06-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='website',
        ),
    ]
