# Generated by Django 3.2.3 on 2021-06-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_remove_apply_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'verbose_name_plural': 'postuler'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'concours'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job', verbose_name='titre de concours'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='letter',
            field=models.TextField(max_length=400, verbose_name='lettre'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nom et prenom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='username',
            field=models.CharField(max_length=40, verbose_name="nom d'utulisateur"),
        ),
        migrations.AlterField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=1, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Description du Concours', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1, help_text="Nombre d'années d'expérience"),
        ),
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Titre de Concours', max_length=150, verbose_name='titre'),
        ),
    ]
